on:
  push:
    branches:
      - master
name: Production Deployment
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🧩 Install Modules
        run: |
          npm install --legacy-peer-deps
          npm install -g yarn

      - name: 👷‍♂️ Build Project
        run: yarn build
        env:
          CI: false

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.DODAM_FILEZILLA_IP }}
          # username: user@tutsplanet.com
          # password: ${{ secrets.DODAM_SCHEDULEPAGE_FTP_PWD }}
