on:
  push:
    branches:
      - master
name: Production Deployment
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🧩 Install Modules
        run: npm install --legacy-peer-deps

      - name: 👷‍♂️ Build Project
        run: npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: http://dodam.b1nd.com
          username: user@tutsplanet.com
          password: ${{ secrets.DODAM_SCHEDULEPAGE_FTP_PWD }}
