on:
  push:
    branches:
      - master
name: Production Deployment
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🧩 Install Modules
        run: |
          npm install --legacy-peer-deps
          npm install -g yarn

      - name: 👷‍♂️ Build Project
        run: yarn build
        env:
          CI: false

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.DODAM_FILEZILLA_IP }}
          username: ${{ secrets.DODAM_FILEZILLA_USERNAME }}
          password: ${{ secrets.DODAM_FILEZILLA_PWD }}
          port: 2021
          local-dir: ./build/
